// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ChatMessage struct {
	ID         int64
	UserID     int64
	ChatRoomID int64
	Content    string
	Created    time.Time
	IsEdited   sql.NullBool
	IsDeleted  sql.NullBool
}

type ChatRoom struct {
	ID          int64
	Name        string
	Description sql.NullString
	Created     time.Time
	IsDeleted   sql.NullBool
}

type User struct {
	ID          int64
	Username    string
	DisplayName string
	Created     time.Time
	IsDeleted   sql.NullBool
}

type UserChatRoom struct {
	UserID     sql.NullInt64
	ChatRoomID sql.NullInt64
}
