// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addUserToChatRoom = `-- name: AddUserToChatRoom :exec
INSERT INTO chats.user_chat_room (
    user_id, chat_room_id
) VALUES ($1, $2)
`

type AddUserToChatRoomParams struct {
	UserID     sql.NullInt64
	ChatRoomID sql.NullInt64
}

func (q *Queries) AddUserToChatRoom(ctx context.Context, arg AddUserToChatRoomParams) error {
	_, err := q.db.ExecContext(ctx, addUserToChatRoom, arg.UserID, arg.ChatRoomID)
	return err
}

const createChatRoom = `-- name: CreateChatRoom :one
INSERT INTO chats.chat_rooms (
    name, description
) VALUES ($1, $2)
RETURNING id, name, description, created, is_deleted
`

type CreateChatRoomParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateChatRoom(ctx context.Context, arg CreateChatRoomParams) (ChatsChatRoom, error) {
	row := q.db.QueryRowContext(ctx, createChatRoom, arg.Name, arg.Description)
	var i ChatsChatRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.IsDeleted,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chats.chat_message (
    user_id, chat_room_id, content, is_edited, is_deleted
) VALUES ($1, $2, $3, FALSE, FALSE)
RETURNING id, user_id, chat_room_id, content, created, is_edited, is_deleted
`

type CreateMessageParams struct {
	UserID     int64
	ChatRoomID int64
	Content    string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatsChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.UserID, arg.ChatRoomID, arg.Content)
	var i ChatsChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatRoomID,
		&i.Content,
		&i.Created,
		&i.IsEdited,
		&i.IsDeleted,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO chats.users (
    username, display_name
) VALUES ($1, $2)
RETURNING id, username, display_name, created, is_deleted
`

type CreateUserParams struct {
	Username    string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ChatsUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.DisplayName)
	var i ChatsUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Created,
		&i.IsDeleted,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM chats.chat_message
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const editMessage = `-- name: EditMessage :exec
UPDATE chats.chat_message
SET content = $2
WHERE id = $1
`

type EditMessageParams struct {
	ID      int64
	Content string
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) error {
	_, err := q.db.ExecContext(ctx, editMessage, arg.ID, arg.Content)
	return err
}

const getChatRoom = `-- name: GetChatRoom :one
SELECT id, name, description, created, is_deleted FROM chats.chat_rooms
WHERE id = $1
`

func (q *Queries) GetChatRoom(ctx context.Context, id int64) (ChatsChatRoom, error) {
	row := q.db.QueryRowContext(ctx, getChatRoom, id)
	var i ChatsChatRoom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Created,
		&i.IsDeleted,
	)
	return i, err
}

const getChatRooms = `-- name: GetChatRooms :many
SELECT id, name, description, created, is_deleted FROM chats.chat_rooms
LIMIT $1
OFFSET $2
`

type GetChatRoomsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetChatRooms(ctx context.Context, arg GetChatRoomsParams) ([]ChatsChatRoom, error) {
	rows, err := q.db.QueryContext(ctx, getChatRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatsChatRoom
	for rows.Next() {
		var i ChatsChatRoom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Created,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, user_id, chat_room_id, content, created, is_edited, is_deleted FROM chats.chat_message
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (ChatsChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i ChatsChatMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChatRoomID,
		&i.Content,
		&i.Created,
		&i.IsEdited,
		&i.IsDeleted,
	)
	return i, err
}

const getMessagesForChatRoom = `-- name: GetMessagesForChatRoom :many
SELECT id, user_id, chat_room_id, content, created, is_edited, is_deleted FROM chats.chat_message
WHERE chat_room_id = $1
LIMIT $2
OFFSET $3
`

type GetMessagesForChatRoomParams struct {
	ChatRoomID int64
	Limit      int32
	Offset     int32
}

func (q *Queries) GetMessagesForChatRoom(ctx context.Context, arg GetMessagesForChatRoomParams) ([]ChatsChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesForChatRoom, arg.ChatRoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatsChatMessage
	for rows.Next() {
		var i ChatsChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChatRoomID,
			&i.Content,
			&i.Created,
			&i.IsEdited,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, display_name, created, is_deleted FROM chats.users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (ChatsUser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i ChatsUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Created,
		&i.IsDeleted,
	)
	return i, err
}
